version: '3.9'

services:
  backend:
    container_name: ikm-retro-backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=IKMRetro;Username=postgres;Password=123
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: ikm-retro-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: IKMRetro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
